import { AxiosResponse } from 'axios'

import { ModelsRedux, ModelsUI } from 'types'

export const isDevMode = true // TODO

export const districtList: ModelsRedux.IDistrictItem[] = [
    { id: 1, title: 'Адмиралтейский', isChecked: true },
    { id: 2, title: 'Василеостровский', isChecked: true },
    { id: 3, title: 'Выборгский', isChecked: true },
    { id: 4, title: 'Калининский', isChecked: true },
    { id: 5, title: 'Кировский', isChecked: true },
    { id: 6, title: 'Колпинский', isChecked: true },
    { id: 7, title: 'Красногвардейский', isChecked: true },
    { id: 8, title: 'Красносельский', isChecked: true },
    { id: 9, title: 'Кронштадтский', isChecked: true },
    { id: 10, title: 'Курортный', isChecked: true },
    { id: 11, title: 'Московский', isChecked: true },
    { id: 12, title: 'Невский', isChecked: true },
    { id: 13, title: 'Петроградский', isChecked: true },
    { id: 14, title: 'Петродворцовый', isChecked: true },
    { id: 15, title: 'Приморский', isChecked: true },
    { id: 16, title: 'Пушкинский', isChecked: true },
    { id: 17, title: 'Фрунзенский', isChecked: true },
    { id: 18, title: 'Центральный', isChecked: true },
]

export const categoryItemsList: ModelsUI.IButtonGroupItem[] = [
    { id: '1', title: 'Кафе', isActive: true, icon: 'Coffee' },
    { id: '2', title: 'Бары', isActive: false, icon: 'TropicalDrink' },
    { id: '3', title: 'Рестораны', isActive: false, icon: 'Bowl' },
    { id: '4', title: 'Парки', isActive: false, icon: 'Tree' },
]

export const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/

export const metroList: string[] = [
    'Девяткино',
    'Гражданский проспект',
    'Академическая',
    'Политехническая',
    'Площадь мужества',
    'Лесная',
    'Выборгская',
    'Площадь Ленина',
    'Чернышевская',
    'Площадь Восстания',
    'Владимирская',
    'Пушкинская',
    'Технологический институт - 1',
    'Балтийская',
    'Нарвская',
    'Кировский завод',
    'Автово',
    'Ленинский проспект',
    'Проспект Ветеранов',
    'Парнас',
    'Проспект Просвещения',
    'Озерки',
    'Удельная',
    'Пионерская',
    'Черная речка',
    'Петроградская',
    'Горьковская',
    'Невский проспект',
    'Сенная площадь',
    'Технологический институт - 2',
    'Фрунзенская',
    'Московские ворота',
    'Электросила',
    'Парк Победы',
    'Московская',
    'Звездная',
    'Купчино',
    'Приморская',
    'Василеостровская',
    'Гостиный двор',
    'Маяковская',
    'Площадь Александра Невского - 1',
    'Елизаровская',
    'Ломоносовская',
    'Пролетарская',
    'Обухово',
    'Рыбацкое',
    'Спасская',
    'Достоевская',
    'Лиговский проспект',
    'Площадь Александра Невского - 2',
    'Новочеркасская',
    'Ладожская',
    'Проспект Большевиков',
    'Улица Дыбенко',
    'Комендантский проспект',
    'Старая Деревня',
    'Крестовский остров',
    'Чкаловская',
    'Спортивная',
    'Адмиралтейская',
    'Садовая',
    'Звенигородская',
    'Обводный канал',
    'Волковская',
    'Бухарестская',
    'Международная',
]

export const axiosSuccessResponseMock: AxiosResponse = {
    data: null,
    status: 200,
    statusText: '',
    headers: null,
    config: {},
}

export const axiosSuccessFailureMock: AxiosResponse = {
    data: null,
    status: 400,
    statusText: '',
    headers: null,
    config: {},
}
